// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSc9o2BBYoXBpzi0NAPJ01dGCn4gvxrOQ',
    appId: '1:1056205342235:web:562f4d34125817ca6b1abe',
    messagingSenderId: '1056205342235',
    projectId: 'nelshop-1c74c',
    authDomain: 'nelshop-1c74c.firebaseapp.com',
    storageBucket: 'nelshop-1c74c.appspot.com',
    measurementId: 'G-0F5P0BZKR5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4LnYoBH1EyF09qUBk54OAUqkTBIbDMy0',
    appId: '1:1056205342235:android:1b92a02f0b48900c6b1abe',
    messagingSenderId: '1056205342235',
    projectId: 'nelshop-1c74c',
    storageBucket: 'nelshop-1c74c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoCBN0fMyHT1QgddgWpQ_8vUVJQADQuZU',
    appId: '1:1056205342235:ios:5b52a4f6e83da0dc6b1abe',
    messagingSenderId: '1056205342235',
    projectId: 'nelshop-1c74c',
    storageBucket: 'nelshop-1c74c.appspot.com',
    iosBundleId: 'com.example.flutterNelshop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoCBN0fMyHT1QgddgWpQ_8vUVJQADQuZU',
    appId: '1:1056205342235:ios:5b52a4f6e83da0dc6b1abe',
    messagingSenderId: '1056205342235',
    projectId: 'nelshop-1c74c',
    storageBucket: 'nelshop-1c74c.appspot.com',
    iosBundleId: 'com.example.flutterNelshop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSc9o2BBYoXBpzi0NAPJ01dGCn4gvxrOQ',
    appId: '1:1056205342235:web:bc2bcaa7353b39236b1abe',
    messagingSenderId: '1056205342235',
    projectId: 'nelshop-1c74c',
    authDomain: 'nelshop-1c74c.firebaseapp.com',
    storageBucket: 'nelshop-1c74c.appspot.com',
    measurementId: 'G-1PTCHB5VM5',
  );

}